apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: simple-nginx
spec:
  type: NodePort
  selector:
    app: simple-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
